from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/image-upload/', views.image_upload, name="image_upload"),
    path('profile/edit/', views.edit_user, name="edit_user"),
    path('profile/', views.profile, name='profile'),
    path('messages/list/', views.messages, name='messages'),
    path('messages/<int:pk>/', views.message, name='message'),
    path('messages/send/', views.send_message, name='send'),
    path('team/list/', views.team, name='team'),
    path('team/new/', views.add_employee, name='add_employee'),
    path('team/<int:pk>/', views.team_member, name='team_member'),
    path('items/list/', views.items, name='items'),
    path('items/new/', views.add_item, name='add_item'),
    path('items/<slug:pk>/', views.item, name='item'),
    path('items/<slug:pk>/edit/', views.edit_item, name='edit_item'),
    path('items/<slug:pk>/request/', views.request_item, name='request_item'),
    path('items/<slug:pk>/delete/', views.delete_item, name='delete_item'),
    path('requests/pending/', views.pending_requests, name='pending_requests'),
    path('categories/new/', views.add_category, name='add_category'),
    path('locations/new/', views.add_location, name='add_location'),
    # path('dashboard/export/', views.pdf, name='export_pdf'),
    path('user-not-found/', views.error, name='page_not_found'),
    path('place-order/', views.place_order, name='place_order'),
    path('verify/<int:pk>/', views.verify, name='verify'),
    path('purchase-orders/', views.purchase_orders, name='purchase_orders'),
    path('suppliers/list/', views.suppliers, name='suppliers'),
    path('suppliers/<int:pk>/', views.supplier, name='supplier'),
    path('suppliers/new/', views.add_supplier, name='add_supplier'),
    path('ajax/load-locations/', views.load_locations,
         name='ajax_load_locations'),
]
