# Generated by Django 2.2.7 on 2019-12-27 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='allocations_overseen', to=settings.AUTH_USER_MODEL),
        ),
    ]
