# Generated by Django 2.2.7 on 2019-12-20 01:40

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191220_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to=dashboard.models.user_directory_path),
        ),
    ]
