# Generated by Django 2.2.7 on 2020-01-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0002_auto_20200110_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
