# Generated by Django 2.2.7 on 2020-08-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0003_auto_20200110_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
