# Generated by Django 2.2.7 on 2019-12-20 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191220_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_company_admin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_company_superuser',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_company_verified',
        ),
        migrations.AlterField(
            model_name='allocation',
            name='approver',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__pk': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allocations_overseen', to=settings.AUTH_USER_MODEL),
        ),
    ]
