# Generated by Django 2.2.7 on 2019-12-30 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0003_message_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name="Vendor's Email Address",
            new_name='vendor',
        ),
    ]
