# Generated by Django 2.2.7 on 2020-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0004_auto_20191230_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
