# Generated by Django 2.2.7 on 2020-08-08 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200802_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='vendor',
        ),
        migrations.AddField(
            model_name='equipment',
            name='average_daily_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='average_lead_time',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(default=5,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='dashboard.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='maximum_daily_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maximum_lead_time',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(
                choices=[('Very Poor', 'VP'), ('Fair', 'F'), ('Good', 'G'),
                         ('Excellent', 'E')], max_length=20),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='dashboard.Company')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(
                    choices=[('Queued', 'Q'), ('Sent', 'S'),
                             ('Cancelled', 'C'), ('Fulfilled', 'F')],
                    max_length=20)),
                ('equipment', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='dashboard.Equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='dashboard.Supplier'),
            preserve_default=False,
        ),
    ]
