# Generated by Django 2.2.7 on 2020-01-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0005_equipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlog',
            name='assets',
            field=models.FloatField(default=0),
        ),
    ]
