# Generated by Django 2.2.7 on 2020-08-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0005_auto_20200808_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='reorder_point',
            field=models.IntegerField(default=1),
        ),
    ]
