# Generated by Django 2.2.7 on 2020-08-09 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0006_equipment_reorder_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='serial',
            new_name='SKU',
        ),
        migrations.AlterField(
            model_name='allocation',
            name='equipment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='dashboard.Equipment', to_field='SKU'),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='equipment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='dashboard.Equipment', to_field='SKU'),
        ),
    ]
