# Generated by Django 2.2.7 on 2020-01-05 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0007_auto_20200105_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email_verified',
        ),
    ]
