# Generated by Django 2.2.7 on 2020-08-09 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0007_auto_20200809_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='equipment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='dashboard.Equipment'),
        ),
        migrations.AlterField(
            model_name='purchaselog',
            name='equipment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='dashboard.Equipment'),
        ),
    ]
