# Generated by Django 2.2.7 on 2020-01-06 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0008_remove_employee_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='returned',
            new_name='checked_in',
        ),
    ]
