# Generated by Django 2.2.7 on 2020-08-09 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0008_auto_20200809_0315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Item',
        ),
    ]
