# Generated by Django 2.2.7 on 2020-08-09 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0009_auto_20200809_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='equipment',
        ),
        migrations.AddField(
            model_name='allocation',
            name='item',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='dashboard.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaselog',
            name='item',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='dashboard.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allocation',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='item_allocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
