# Generated by Django 2.2.7 on 2020-08-09 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0010_auto_20200809_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(
                    choices=[('Queued', 'Q'), ('Sent', 'S'),
                             ('Cancelled', 'C'), ('Fulfilled', 'F')],
                    max_length=20)),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='dashboard.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseLog',
        ),
    ]
