# Generated by Django 2.2.7 on 2020-08-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0011_auto_20200809_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_purchased',
            field=models.IntegerField(default=1),
        ),
    ]
