# Generated by Django 2.2.7 on 2020-08-09 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0012_auto_20200809_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(
                    choices=[('Pending', 'P'), ('Fulfilled', 'F'),
                             ('Stock Out', 'S')], max_length=20)),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='dashboard.Item')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='item_requests',
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
    ]
