# Generated by Django 2.2.7 on 2020-08-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0013_auto_20200809_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(
                choices=[('Pending', 'P'), ('Fulfilled', 'F'),
                         ('Stock Out', 'S'), ('Returned', 'R')],
                max_length=20),
        ),
    ]
