# Generated by Django 2.2.7 on 2020-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0014_auto_20200809_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(
                choices=[('Pending', 'P'), ('Fulfilled', 'F'),
                         ('Stock Out', 'S'), ('Returned', 'R')], default='P',
                max_length=20),
        ),
    ]
