# Generated by Django 2.2.7 on 2020-08-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0015_auto_20200809_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
