# Generated by Django 2.2.7 on 2020-08-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0016_auto_20200809_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(
                choices=[('P', 'Pending'), ('F', 'Fulfilled'),
                         ('SO', 'Stock Out'), ('R', 'Returned')], default='P',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(
                choices=[('Q', 'Queued'), ('S', 'Sent'), ('C', 'Cancelled'),
                         ('F', 'Fulfilled')], max_length=20),
        ),
    ]
