# Generated by Django 2.2.7 on 2020-08-10 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0017_auto_20200810_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('month', models.CharField(
                    choices=[('Jan', 'January'), ('Feb', 'February'),
                             ('Mar', 'March'), ('Apr', 'April'),
                             ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'),
                             ('Aug', 'August'), ('Sep', 'September'),
                             ('Oct', 'October'), ('Nov', 'November'),
                             ('Dec', 'December')], max_length=20)),
                ('year', models.IntegerField()),
                ('inventory_value', models.FloatField(default=0)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='dashboard.Company')),
            ],
        ),
        migrations.DeleteModel(
            name='AssetLog',
        ),
    ]
