# Generated by Django 2.2.7 on 2020-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0018_auto_20200810_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_returnable',
            field=models.BooleanField(default=False),
        ),
    ]
