# Generated by Django 2.2.7 on 2020-08-24 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0019_item_is_returnable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('is_returned', models.BooleanField(default=False)),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('fulfil_date', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='returns_to_inventory',
                    to='dashboard.ItemRequest')),
            ],
        ),
    ]
