# Generated by Django 2.2.7 on 2020-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0020_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(
                choices=[('P', 'Pending'), ('F', 'Fulfilled'),
                         ('SO', 'Stock Out')], default='P', max_length=20),
        ),
    ]
