# Generated by Django 2.2.7 on 2020-08-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0021_auto_20200824_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(
                choices=[('P', 'Pending'), ('F', 'Fulfilled'),
                         ('C', 'Cancelled'), ('SO', 'Stock Out')], default='P',
                max_length=20),
        ),
    ]
