# Generated by Django 2.2.7 on 2020-08-26 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0022_auto_20200826_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='ItemReturn',
        ),
    ]
