# Generated by Django 2.2.7 on 2020-09-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0023_auto_20200826_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True,
                                      help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                      verbose_name='active'),
        ),
    ]
