"""
Django settings for crystalims project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

from .config import *

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qq21%w7$1yy5rv5zd%png$fzi)_&@5j%4lm63vem&!a4*yul3p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

SOCIAL_AUTH_TWITTER_KEY = '8SvoFgdWewZmHgVyNRbc115yq'
SOCIAL_AUTH_TWITTER_SECRET = '91rNgDAMylDXBUbOUDIOz6inyha2xwWQ5Ymi1UrTARC2RPrBVH'
SOCIAL_AUTH_FACEBOOK_KEY = '896788630844040'
SOCIAL_AUTH_FACEBOOK_SECRET = 'daaf3638224607798832c3be53f65a9a'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '336008437255-df9o38359lkk7n26jsslhas7dh9v2g25.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'Z0e3jXZDhRmKWhYGOdCP0u3C'
SOCIAL_AUTH_SLUGIFY_USERNAMES = True
SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['company_id']
SOCIAL_AUTH_GOOGLE_OAUTH2_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.debug.debug',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',

    'dashboard.pipeline.identify_company',

    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'social_core.pipeline.debug.debug',
)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.mailgun.org'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'postmaster@sandbox4ea32e534f5b45aea37dc52c33a8ddb7.mailgun.org'
EMAIL_HOST_PASSWORD = '19e4f5482909c4c49e9919b533814957-7fba8a4e-f8402762'

DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = 'crystal-ims.appspot.com'
GS_FILE_OVERWRITE = False
GOOGLE_APPLICATION_CREDENTIALS = os.path.join(BASE_DIR,
                                              'crystal-eba453ba4522.json')
GOOGLE_CLOUD_PROJECT = 'crystalims'
GS_PROJECT_ID = 'crystal-ims'

ALLOWED_HOSTS = ['127.0.0.1',
                 'crystalinventorymanagementsystem-env.zx3sytpbnp.us-east-2.elasticbeanstalk.com',
                 'crystal-ims.appspot.com', 'staging.crystal-ims.appspot.com']

ADMINS = [('Elizabeth', 'adeotunadegbaju@gmail.com')]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'django.contrib.humanize',
    'widget_tweaks',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'crystalims.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'django.contrib.auth.backends.ModelBackend',
)

WSGI_APPLICATION = 'crystalims.wsgi.application'

AUTH_USER_MODEL = 'dashboard.User'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# [START db_setup]
if os.getenv('GAE_APPLICATION', None):
    # Running on production App Engine, so connect to Google Cloud SQL using
    # the unix socket at /cloudsql/<your-cloudsql-connection string>
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '/cloudsql/crystal-ims:us-east1:crystal',
            'USER': 'adeotun',
            'PASSWORD': '',
            'NAME': 'crystal',
        }
    }
else:
    # Running locally so connect to either a local MySQL instance or connect
    # to Cloud SQL via the proxy.  To start the proxy via command line:
    #    $ vcloud_sql_proxy -instances=crystal-ims:us-east1:crystal=tcp:3306
    # See https://cloud.google.com/sql/docs/mysql-connect-proxy
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'NAME': 'crystal',
            'USER': 'adeotun',
            'PASSWORD': '',
        }
    }
# [END db_setup]


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# STATIC_ROOT = 'static'
MEDIA_ROOT = 'media'
STATIC_URL = '/static/'
if os.getenv('GAE_APPLICATION', None):
    STATIC_ROOT = 'static'
else:
    STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static/'),)
MEDIA_URL = 'https://storage.googleapis.com/crystal-ims.appspot.com/'
